"""add anime and manga library entries

Revision ID: d3f1c1c97a39
Revises: 1789d3b30cc6
Create Date: 2026-07-22 23:33:43.882205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f1c1c97a39'
down_revision: Union[str, None] = '1789d3b30cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WATCHING', 'COMPLETED', 'DROPPED', 'PLAN_TO_WATCH', name='animestatus'), nullable=False),
    sa.Column('current_episode', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_anime')
    )
    op.create_index(op.f('ix_anime_library_entries_id'), 'anime_library_entries', ['id'], unique=False)
    op.create_table('manga_library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('READING', 'COMPLETED', 'DROPPED', 'PLAN_TO_READ', name='mangastatus'), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'manga_id', name='uq_user_manga')
    )
    op.create_index(op.f('ix_manga_library_entries_id'), 'manga_library_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manga_library_entries_id'), table_name='manga_library_entries')
    op.drop_table('manga_library_entries')
    op.drop_index(op.f('ix_anime_library_entries_id'), table_name='anime_library_entries')
    op.drop_table('anime_library_entries')
    # ### end Alembic commands ###
